# This file is part of the MopaBootstrapBundle.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
   twig.extension.mopa.initializr:
       class: 'Mopa\Bundle\BootstrapBundle\Twig\MopaBootstrapInitializrTwigExtension'
       arguments:
          -
             meta: '%mopa_bootstrap.initializr.meta%'
             dns_prefetch: '%mopa_bootstrap.initializr.dns_prefetch%'
             preconnect: '%mopa_bootstrap.initializr.preconnect%'
             prefetch: '%mopa_bootstrap.initializr.prefetch%'
             google: '%mopa_bootstrap.initializr.google%'
             diagnostic_mode: '%mopa_bootstrap.initializr.diagnostic_mode%'
       tags:
          - { name: twig.extension }
